name: 'LumenMCMonitor'
version: 'b1.2'
main: cloud.lumenvm.monitor.Monitor
api-version: "1.18"
authors: ["Lumen Development", "SNVK"]
website: https://lumenvm.cloud/

depend: ["PlaceholderAPI"]

commands:
  lumenmc:
    description: Commands for LumenMC Monitor
    usage: /lumenmc test|lang|reload|webhook|config|send (For full usage visit plugin website)
    permission: lumenmc.admin
permissions:
  lumenmc.admin:
    default: op
