name: 'LumenMCMonitor'
version: 'a1.1'
main: cloud.lumenvm.Monitor
api-version: '1.18'
commands:
  lumenmc:
    description: Testing and relaoding LumenMC DCWebhooks plugin
    usage: /lumenmc test|reload
    permission: lumenmc.admin
permissions:
  lumenmc.admin:
    default: op
