name: 'LumenMCMonitor'
version: 'a1.3'
main: cloud.lumenvm.Monitor
api-version: '1.18'
load: STARTUP
authors: ["Lumen Development", "SNVK"]
website: https://lumenvm.cloud/

softdepend: ["PlaceholderAPI"]

commands:
  lumenmc:
    description: Commands for LumenMC Monitor
    usage: /lumenmc test|lang|reload|setwebhook (For full usage visit plugin website)
    permission: lumenmc.admin
permissions:
  lumenmc.admin:
    default: op
