name: 'LumenMCMonitor'
version: 'b1.2'
main: cloud.lumenvm.monitor.Monitor
api-version: "1.18"
authors: ["Lumen Development", "SNVK"]
website: https://lumenvm.cloud/

depend: ["PlaceholderAPI"]

commands:
  lumenmc:
    description: Commands for LumenMC Monitor
    usage: /lumenmc test|lang|reload|webhook|config|send|user (For full usage visit plugin website)
    permission: lumenmc.admin
  lumenmc user:
    description: User webhooks
    usage: /lumenmc user add|remove|config|list
    permission: lumenmc.player
permissions:
  lumenmc.admin:
    default: op
    children:
      lumenmc.player: true
  lumenmc.player:
    default: not op